### PR TITLE
Add serde implementation to wire messages for wasm_bindgen support

### LINKED ISSUE #16: Implement serde traits for message types to support wasm_bindgen
**Issue summary**

Message types do not implement the serde `Serialize` and `Deserialize` traits which means we can't pass messages across the webassembly/javascript bindings.

I will look into adding `serde` support to `ProtocolMessage` etc so we can create bindings in webassembly.

Just wanted to let you know about this.

**Other information and links**

The `multi-party-ecdsa` library implements `Serialize` and `Deserialize` for all message types and `LocalKey` so that it works with `wasm_bindgen` so I think the CGGMP implementation should to.

Thanks!

### PR DESCRIPTION
**Pull request by tmpfs**
**Summary of changes**
Changes introduced in this pull request:
* [x] Implement serde traits for refresh `ProtocolMessage`
* [x] Implement serde traits for presign `ProtocolMessage`
* [x] Implement serde traits for sign `ProtocolMessage`

**Reference issue to close (if applicable)**

Closes #16

### CODE REVIEW

**Comment by drewstone** [comment]
Apologies for the delay, also merged a similar PR on our fs-dkr fork.

**Comment by drewstone** [comment]
Let me know if you'd like to chat about helping finish up the implementation/testing for the presign/signing rounds too. Unsure what your plan is with the `wasm_bindgen` with the state of presign/sign not entirely working.

**Comment by tmpfs** [comment]
@drewstone, my colleague is looking into completing the presign/sign implementations and we hope to contribute those changes back here, will update later!

**Comment by drewstone** [comment]
Awesome sounds great!

**Pull request merged**
