### PR TITLE
refactor: move mod-prm

### PR DESCRIPTION
**Pull request by ivokub**
WIP pull request. Do not merge!

### CODE REVIEW

**Comment by davidsemakula** [comment]
@ivokub will this cover https://github.com/webb-tools/cggmp-threshold-ecdsa/issues/38 ?
If so I will un-assign myself from that issue

**Comment by ivokub** [comment]
> @ivokub will this cover #38 ? If so I will un-assign myself from that issue

Indeed - I also changed the calls to Ring-Pedersen proof in this PR. Additionally, I defined RingPedersenParams in the new tss-core workspace which I'm using instead of carrying `(N, s, t)` everywhere. Imo makes more readable and allows better refactoring later.

**Comment by davidsemakula** [comment]
Sounds good 👍 
Minor pedantic suggestion, can we start switching to the modern Rust module style i.e. `my_module.rs` instead of `my_module/mod.rs`. We can start this with the new `tss-core` core crate and gradually update the others as we get to refactoring them (I can also do this in a separate PR after this one if it's a lot of monkey work 🙂)

**Comment by ivokub** [comment]
> Sounds good 👍 Minor pedantic suggestion, can we start switching to the modern Rust module style i.e. `my_module.rs` instead of `my_module/mod.rs`. We can start this with the new `tss-core` core crate and gradually update the others as we get to refactoring them (I can also do this in a separate PR after this one if it's a lot of monkey work 🙂)

I can do it in the PR. It is my first Rust project and I wasn't aware of the new style :). I agree that it creates less clutter.

**Comment by drewstone** [comment]
How's it going on this? Any help needed @ivokub

**Comment by ivokub** [comment]
> How's it going on this? Any help needed @ivokub

Hi Drew, was at Devconnect and before that preparing for presentations. Now I'm back with backlog settling, so restarting effort 👍 .

**Comment by drewstone** [comment]
@ivokub if you open PRs directly against the repo (and not in a fork), I can jump in a help fix up the CI. I think you should be in the github org just in case you weren't sure if it was possible.

**Comment by ivokub** [comment]
Closing in favor of #48 which is pushed to this repository for appending.

**Pull request closed without merging**
